// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkcafzwgbljwurbsrszn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrY2FmendnYmxqd3VyYnNyc3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzEzMjUsImV4cCI6MjA2NDUwNzMyNX0.zhHyQclLj5TitH02lNQ3eHj77r_A9uPzUIIW851-8I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);